name: Publish to GitHub Pages
on:
  push:
    branches: [main]
  repository_dispatch:   # ← ¡falta!
    types: [quote]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sustituir placeholders
        run: |
          sed -i "s|{{ secrets.GH_TOKEN }}|${{ secrets.GH_TOKEN }}|g" index.html
          sed -i "s|GOOGLE_API_KEY_AQUI|${{ secrets.GOOGLE_API_KEY }}|g" index.html

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: .          # todo el repo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
