name: Publish to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Insert secrets
        run: |
          sed -i "s|{{ secrets.GH_TOKEN }}|${{ secrets.GH_TOKEN }}|g" index.html
          sed -i "s|GOOGLE_API_KEY_AQUI|${{ secrets.GOOGLE_API_KEY }}|g" index.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .          # sube todo el directorio
          publish_branch: gh-pages # ← importante
